import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from '@next/third-parties/google';

import "./globals.css";
import React from "react";
import favicon from "./favicon.png";
import appleIcon from "./apple-icon.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src,
    apple: appleIcon.src,
  },
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
      <Analytics />
      <GoogleAnalytics gaId="G-PHBMXCD0E6"/>
    </html>
  );
}
