import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { LOCALES } from "@/lib/constants";

import React from "react";
import favicon from "../favicon.png";
import appleIcon from "../apple-icon.png";

export async function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src,
    apple: appleIcon.src,
  },
  robots: {
    index: false,
    follow: false,
  },
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messagesModule = await import(`../../messages/${locale}.json`);
  const messages = messagesModule.default;

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <Providers>{children}</Providers>
    </NextIntlClientProvider>
  );
}
